### PR TITLE
Set minimum python version 3.11

### PR DESCRIPTION
**Pull request by rilysh**
Debian 12 comes with Python 3.11, however, poetry dependency version is set to 3.12. Without ignoring the version, it's not possible to install it using pip, and since changy doesn't seem to require minimum 3.12, I think it's better to lower it down.

### CODE REVIEW

**Comment by Tiendil** [comment]
Good point!

Could you run `poetry lock --no-update` and add `poetry.lock` file to this PR?

If not, I'll reduce the Python version myself.

**Comment by Tiendil** [comment]
And `docker/Dockerfile` should be updated too.

**Comment by rilysh** [comment]
okay, updated.

**Comment by Tiendil** [comment]
Thank you for your efforts!

Version 0.4.3 with your fix was uploaded to pypi.

**Pull request merged**
